site_name: Hadiro API Docs
theme:
  name: material
  palette:
    primary: custom

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        id: Bahasa Indonesia

nav:
  - Home: index.md
  - Beranda: index.id.md