site_name: Hadiro API Docs
theme:
  name: material
  logo: https://raw.githubusercontent.com/literal-metaphor/hadiro/refs/heads/main/server/docs/assets/logo.png
  favicon: https://raw.githubusercontent.com/literal-metaphor/hadiro/refs/heads/main/server/docs/assets/logo.png
  language: en
  palette:
    primary: custom

extra_css:
  - stylesheets/extra.css

extra:
  homepage: https://github.com/literal-metaphor/hadiro
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Bahasa Indonesia
      link: /id/
      lang: id

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        id: Bahasa Indonesia

nav:
  - Home: index.md
  - Beranda: index.id.md